services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: yarn dev
    ports:
      - 3000:8000
    depends_on:
      - redis
    environment:
      NODE_ENV: development

  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"

volumes:
  redis:
    driver: local